### ISSUE TITLE
uvicMuse not starting on Osx 11.0.1

### ISSUE THREAD

**Issue by soreno123** [bardiabarabadi/uvicMUSE#7] opened 2020-12-13 12:55 UTC
Hello,
i've got a MUSE-02 and since i'm unable (apparently) to use my BLE usb dongle, i'm trying to use uvicMUSE with the internal Bluetooth of the Mac (Macbook Pro 2019 16').
But as soon as i start it it crashes with no error message.
I've tried 

On MacOSx: Application crashes after running:

pip uninstall serial pyserial
pip install pyserial esptool

But nothing changed.
Any Hint?
Thanks,
Soreno

**Comment by soreno123** [comment] 2020-12-13 20:53
Update:
I reinstalled uvicmuse and now when i start it i get this error:

INFO   ] [Logger      ] Record log in /var/root/.kivy/logs/kivy_20-12-13_1.txt
[INFO   ] [Kivy        ] v2.0.0rc4, git-d74461b, 20201015
[INFO   ] [Kivy        ] Installed at "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)
[Clang 6.0 (clang-600.0.57)]
[INFO   ] [Python      ] Interpreter at "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9"
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "/Library/Frameworks/Python.framework/Versions/3.9/bin/uvicmuse", line 5, in <module>
     from uvicmuse.__main__ import main
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uvicmuse/__main__.py", line 3, in <module>
     from uvicmuse.interface import runGUI
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uvicmuse/interface.py", line 9, in <module>
     from kivy.app import App
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/base.py", line 28, in <module>
     from kivy.clock import Clock
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'

**Comment by bardiabarabadi** [comment] 2020-12-13 21:28
Hello, it seems like the problem is caused by Kivy. Try these:

1. Reinstall uvicmuse using the --force-reinstall flag for pip. Also, make sure you are installing the latest version (5.2.1)
2. Follow this instruction to install and compile Kivy: [https://kivy.org/doc/master/gettingstarted/installation.html#install-conda](https://kivy.org/doc/master/gettingstarted/installation.html#install-conda)
3. I can see that you are using python 3.9.1. If the above solutions do not work, try making a new conda environment with python=3.8

**Comment by soreno123** [comment] 2020-12-13 23:11
Hello,
I've remove python 3.9 and installed 3.8.
Now it starts, but when i look for muse it says
"No BLE Module Found"
![image](https://user-images.githubusercontent.com/36479898/102026748-f4bc2f00-3d9f-11eb-8659-344e0a730c2d.png)
That's my BT info.
![image](https://user-images.githubusercontent.com/36479898/102026884-dd317600-3da0-11eb-8d10-b3527e18e096.png)
Any hint?
Thanks a lot

**Comment by bardiabarabadi** [comment] 2020-12-13 23:23
- First, let's make sure that the terminal has access to Bluetooth. Go to your system preferences and make sure it looks like this:

![Screen Shot 2020-12-13 at 3 16 49 PM](https://user-images.githubusercontent.com/12707895/102027007-3a540a00-3d56-11eb-9d80-78b7c4fe6c2e.png)

- Open a python shell (on the same environment as you installed uvicmuse) and write down this code. Post the outputs here.

`from uvicmuse.MuseWrapper import MuseWrapper as MW`
`import asyncio`
`loop = asyncio.get_event_loop()`
`M_wrapper = MW (loop = loop,
                    target_name = None,
                    timeout = 10,
                    max_buff_len = 500) `
`M_wrapper.search_and_connect() # returnes True if the connection is successful`
`EEG_data = M_wrapper.pull_eeg()   `
`EEG_data = M_wrapper.pull_eeg()`
`print (str(EEG_data))`
`M_wrapper.disconnect()`

**Comment by soreno123** [comment] 2020-12-14 09:00
Hello,
after giving permission to iTerm it worked.
![image](https://user-images.githubusercontent.com/36479898/102060872-067af200-3df3-11eb-9b66-7cdf38f6a797.png)
Thanks for the support!

**Comment by bardiabarabadi** [comment] 2020-12-14 16:29
Glad to hear that. Closing the issue.

**Closed as completed by bardiabarabadi** 2020-12-14 16:29 UTC
