### ISSUE TITLE
AUX eeg

### ISSUE THREAD

**Issue by paulabrennan** [bardiabarabadi/uvicMUSE#10] opened 2021-02-09 02:19 UTC
Hi there, 

Just noting that I can get the eeg data stream from the four basic sensors, but the AUX channel is all zeros for me. I see the the aux channel is mentioned in the code, so wondering if this is an issue with how I'm accessing the stream. 
Comparing with BlueMuse, with which I am able to see the AUX eeg data using the same access method. Thanks, Paul

**Comment by bardiabarabadi** [comment] 2021-02-20 02:52
Sorry for the delay,
I am looking at the code right now, it seems like that you need to access the fifth element of the EEG array to get the AUX data. In other words, the AUX data comes just like another EEG channel. Since I don’t have any device to use as an AUX input, I can’t test it. Please take a look and let me know if that is actually the case.

**Comment by paulabrennan** [comment] 2021-02-20 03:37
Bardia, I’m getting this: 

From print(timestamp, sample): 

paulbrennan@Pauls-MacBook-Air python % python3 ReceiveData.py
looking for an EEG stream...
1613792161.545386 [49.8046875, 55.17578125, 124.51171875, -20.99609375, 0.0]
1613792161.5492923 [27.83203125, 290.52734375, 225.09765625, 6.8359375, 0.0]
1613792161.5531986 [23.92578125, 235.3515625, 238.76953125, -11.71875, 0.0]
1613792161.5571048 [29.78515625, -36.1328125, 146.97265625, -50.29296875, 0.0]
1613792161.561011 [42.96875, 30.76171875, 114.74609375, -4.39453125, 0.0]
1613792161.5649173 [-7.32421875, 131.8359375, 212.890625, -13.18359375, 0.0]
1613792161.5688236 [-25.390625, 135.25390625, 247.55859375, -8.7890625, 0.0]
1613792161.5727298 [30.2734375, -3.90625, 152.34375, -34.66796875, 0.0]

**Comment by paulabrennan** [comment] 2021-02-20 03:38
There is an electrode connected and it’s working under BlueMuse…..

**Comment by bardiabarabadi** [comment] 2021-02-20 03:59
I will take a look and get back to you as soon as I can.

**Comment by paulabrennan** [comment] 2021-02-20 04:23
No worries, thank you Bardia! Happy to retest, etc. 

Paul Brennan, RPsych
Registered Psychologist (BC # 2363)
Tel:(780) 217 6715

**Comment by bardiabarabadi** [comment] 2021-02-20 05:30
can you tell me which version are you using using this command:
`pip show uvicmuse`

**Comment by bardiabarabadi** [comment] 2021-02-20 06:00
So I need to test something to get a better idea of the issue. However, since I don't have access to an external electrode, I would appreciate it if you can do it for me. All you have to do is to update uvicmuse to a dev version (with the pip code below) and send me the terminal output of the code while it is connected to the AUX and streaming. 

`pip install uvicmuse==5.3.0.dev0`

P.S. I assume that you have been using the no-dongle version (5.0 or greater) until now.

**Comment by paulabrennan** [comment] 2021-02-20 07:47
Hi there for sure I’ll test it in the morning and get back to you

Paul Brennan RPsych
P:(780) 217 6715
www.victoriatherapist.com

**Comment by paulabrennan** [comment] 2021-02-20 17:03
HI Bardia - that output is attached. I’ve been running 5.2.1 till now, no dongle. This is on MacOS.  On Windows I’ve been using BlueMuse, which does output the AUX. 

Hope this helps, Paul

Paul Brennan, RPsych
Registered Psychologist (BC # 2363)
Tel:(780) 217 6715

**Comment by bardiabarabadi** [comment] 2021-02-21 00:43
The issue is resolved in version 5.3.2
I am closing this thread. 
Cheers

**Closed as completed by bardiabarabadi** 2021-02-21 00:43 UTC
